GMOCK_BUILD_DIRECTORY='gmock-1.6.0/build'
LIBRARY_BUILD_DIRECTORY='library/build'
LIBRARY_INSTALLATION_DIRECTORY='test_installation'
LIBCPPMANIP_INSTALLATION_INCLUDE=LIBRARY_INSTALLATION_DIRECTORY + '/usr/local/include'
LIBCPPMANIP_INSTALLATION_LIB=LIBRARY_INSTALLATION_DIRECTORY + '/usr/local/lib'
RUNNER_BUILD_DIRECTORY='runner/build'

